2025-09-19 14:41:22,709 [INFO] __main__: Start
2025-09-19 14:41:22,712 [INFO] __main__: SYNC_MODE=OBJECTS
2025-09-19 14:41:22,712 [INFO] __main__: Starting object upload (parent 177537954)
2025-09-19 14:41:22,712 [DEBUG] sf_object_loader: Running CLI: C:\Program Files\sf\bin\sf.cmd sobject list --json -o Prod
2025-09-19 14:41:24,818 [INFO] sf_object_loader: LIMIT_OBJECTS enabled, restricting to first 10 objects
2025-09-19 14:41:24,819 [INFO] sf_object_loader: Describing object: AC_Corp_Form__ChangeEvent
2025-09-19 14:41:24,819 [DEBUG] sf_object_loader: Running CLI: C:\Program Files\sf\bin\sf.cmd sobject describe -s AC_Corp_Form__ChangeEvent --json -o Prod
2025-09-19 14:41:26,385 [INFO] sf_object_loader: Describing object: AC_Corp_Form__Share
2025-09-19 14:41:26,385 [DEBUG] sf_object_loader: Running CLI: C:\Program Files\sf\bin\sf.cmd sobject describe -s AC_Corp_Form__Share --json -o Prod
2025-09-19 14:41:27,957 [INFO] sf_object_loader: Describing object: AC_Corp_Form__c
2025-09-19 14:41:27,958 [DEBUG] sf_object_loader: Running CLI: C:\Program Files\sf\bin\sf.cmd sobject describe -s AC_Corp_Form__c --json -o Prod
2025-09-19 14:41:29,699 [INFO] sf_object_loader: Describing object: AIApplication
2025-09-19 14:41:29,700 [DEBUG] sf_object_loader: Running CLI: C:\Program Files\sf\bin\sf.cmd sobject describe -s AIApplication --json -o Prod
2025-09-19 14:41:31,285 [INFO] sf_object_loader: Describing object: AIApplicationConfig
2025-09-19 14:41:31,285 [DEBUG] sf_object_loader: Running CLI: C:\Program Files\sf\bin\sf.cmd sobject describe -s AIApplicationConfig --json -o Prod
2025-09-19 14:41:32,903 [INFO] sf_object_loader: Describing object: AIInsightAction
2025-09-19 14:41:32,903 [DEBUG] sf_object_loader: Running CLI: C:\Program Files\sf\bin\sf.cmd sobject describe -s AIInsightAction --json -o Prod
2025-09-19 14:41:34,440 [INFO] sf_object_loader: Describing object: AIInsightFeedback
2025-09-19 14:41:34,440 [DEBUG] sf_object_loader: Running CLI: C:\Program Files\sf\bin\sf.cmd sobject describe -s AIInsightFeedback --json -o Prod
2025-09-19 14:41:36,000 [INFO] sf_object_loader: Describing object: AIInsightReason
2025-09-19 14:41:36,000 [DEBUG] sf_object_loader: Running CLI: C:\Program Files\sf\bin\sf.cmd sobject describe -s AIInsightReason --json -o Prod
2025-09-19 14:41:37,536 [INFO] sf_object_loader: Describing object: AIInsightValue
2025-09-19 14:41:37,537 [DEBUG] sf_object_loader: Running CLI: C:\Program Files\sf\bin\sf.cmd sobject describe -s AIInsightValue --json -o Prod
2025-09-19 14:41:40,152 [INFO] sf_object_loader: Describing object: AIPredictionEvent
2025-09-19 14:41:40,152 [DEBUG] sf_object_loader: Running CLI: C:\Program Files\sf\bin\sf.cmd sobject describe -s AIPredictionEvent --json -o Prod
2025-09-19 14:41:41,680 [INFO] __main__: Uploading object: AC_Corp_Form__ChangeEvent
2025-09-19 14:41:41,682 [DEBUG] urllib3.connectionpool: Starting new HTTPS connection (1): cretemechanical.atlassian.net:443
2025-09-19 14:41:41,769 [DEBUG] urllib3.connectionpool: https://cretemechanical.atlassian.net:443 "GET /wiki/api/v2/pages?spaceId=28180482&title=AC_Corp_Form__ChangeEvent&expand=version HTTP/1.1" 200 None
2025-09-19 14:41:41,770 [ERROR] __main__: Failed to upload object AC_Corp_Form__ChangeEvent
Traceback (most recent call last):
  File "C:\Users\vm-bpa\OneDrive - Crete Mechanical\Code\UploadFlowDocumentation\main.py", line 51, in process_objects
    uploader.upload_object_doc(parent_id=parent_id, object_name=obj_name, fields=fields, meta=meta)
  File "C:\Users\vm-bpa\OneDrive - Crete Mechanical\Code\UploadFlowDocumentation\confluence_uploader.py", line 200, in upload_object_doc
    for cr in meta.get("childRelationships", []):
TypeError: 'int' object is not iterable
2025-09-19 14:41:41,771 [INFO] __main__: Uploading object: AC_Corp_Form__Share
2025-09-19 14:41:41,772 [DEBUG] urllib3.connectionpool: Starting new HTTPS connection (1): cretemechanical.atlassian.net:443
2025-09-19 14:41:41,868 [DEBUG] urllib3.connectionpool: https://cretemechanical.atlassian.net:443 "GET /wiki/api/v2/pages?spaceId=28180482&title=AC_Corp_Form__Share&expand=version HTTP/1.1" 200 None
2025-09-19 14:41:41,870 [ERROR] __main__: Failed to upload object AC_Corp_Form__Share
Traceback (most recent call last):
  File "C:\Users\vm-bpa\OneDrive - Crete Mechanical\Code\UploadFlowDocumentation\main.py", line 51, in process_objects
    uploader.upload_object_doc(parent_id=parent_id, object_name=obj_name, fields=fields, meta=meta)
  File "C:\Users\vm-bpa\OneDrive - Crete Mechanical\Code\UploadFlowDocumentation\confluence_uploader.py", line 200, in upload_object_doc
    for cr in meta.get("childRelationships", []):
TypeError: 'int' object is not iterable
2025-09-19 14:41:41,870 [INFO] __main__: Uploading object: AC_Corp_Form__c
2025-09-19 14:41:41,872 [DEBUG] urllib3.connectionpool: Starting new HTTPS connection (1): cretemechanical.atlassian.net:443
2025-09-19 14:41:41,976 [DEBUG] urllib3.connectionpool: https://cretemechanical.atlassian.net:443 "GET /wiki/api/v2/pages?spaceId=28180482&title=AC_Corp_Form__c&expand=version HTTP/1.1" 200 None
2025-09-19 14:41:41,977 [ERROR] __main__: Failed to upload object AC_Corp_Form__c
Traceback (most recent call last):
  File "C:\Users\vm-bpa\OneDrive - Crete Mechanical\Code\UploadFlowDocumentation\main.py", line 51, in process_objects
    uploader.upload_object_doc(parent_id=parent_id, object_name=obj_name, fields=fields, meta=meta)
  File "C:\Users\vm-bpa\OneDrive - Crete Mechanical\Code\UploadFlowDocumentation\confluence_uploader.py", line 145, in upload_object_doc
    [
TypeError: 'int' object is not iterable
2025-09-19 14:41:41,977 [INFO] __main__: Uploading object: AIApplication
2025-09-19 14:41:41,978 [DEBUG] urllib3.connectionpool: Starting new HTTPS connection (1): cretemechanical.atlassian.net:443
2025-09-19 14:41:42,061 [DEBUG] urllib3.connectionpool: https://cretemechanical.atlassian.net:443 "GET /wiki/api/v2/pages?spaceId=28180482&title=AIApplication&expand=version HTTP/1.1" 200 None
2025-09-19 14:41:42,062 [ERROR] __main__: Failed to upload object AIApplication
Traceback (most recent call last):
  File "C:\Users\vm-bpa\OneDrive - Crete Mechanical\Code\UploadFlowDocumentation\main.py", line 51, in process_objects
    uploader.upload_object_doc(parent_id=parent_id, object_name=obj_name, fields=fields, meta=meta)
  File "C:\Users\vm-bpa\OneDrive - Crete Mechanical\Code\UploadFlowDocumentation\confluence_uploader.py", line 200, in upload_object_doc
    for cr in meta.get("childRelationships", []):
TypeError: 'int' object is not iterable
2025-09-19 14:41:42,062 [INFO] __main__: Uploading object: AIApplicationConfig
2025-09-19 14:41:42,063 [DEBUG] urllib3.connectionpool: Starting new HTTPS connection (1): cretemechanical.atlassian.net:443
2025-09-19 14:41:42,148 [DEBUG] urllib3.connectionpool: https://cretemechanical.atlassian.net:443 "GET /wiki/api/v2/pages?spaceId=28180482&title=AIApplicationConfig&expand=version HTTP/1.1" 200 None
2025-09-19 14:41:42,149 [ERROR] __main__: Failed to upload object AIApplicationConfig
Traceback (most recent call last):
  File "C:\Users\vm-bpa\OneDrive - Crete Mechanical\Code\UploadFlowDocumentation\main.py", line 51, in process_objects
    uploader.upload_object_doc(parent_id=parent_id, object_name=obj_name, fields=fields, meta=meta)
  File "C:\Users\vm-bpa\OneDrive - Crete Mechanical\Code\UploadFlowDocumentation\confluence_uploader.py", line 200, in upload_object_doc
    for cr in meta.get("childRelationships", []):
TypeError: 'int' object is not iterable
2025-09-19 14:41:42,149 [INFO] __main__: Uploading object: AIInsightAction
2025-09-19 14:41:42,150 [DEBUG] urllib3.connectionpool: Starting new HTTPS connection (1): cretemechanical.atlassian.net:443
2025-09-19 14:41:42,246 [DEBUG] urllib3.connectionpool: https://cretemechanical.atlassian.net:443 "GET /wiki/api/v2/pages?spaceId=28180482&title=AIInsightAction&expand=version HTTP/1.1" 200 None
2025-09-19 14:41:42,247 [ERROR] __main__: Failed to upload object AIInsightAction
Traceback (most recent call last):
  File "C:\Users\vm-bpa\OneDrive - Crete Mechanical\Code\UploadFlowDocumentation\main.py", line 51, in process_objects
    uploader.upload_object_doc(parent_id=parent_id, object_name=obj_name, fields=fields, meta=meta)
  File "C:\Users\vm-bpa\OneDrive - Crete Mechanical\Code\UploadFlowDocumentation\confluence_uploader.py", line 145, in upload_object_doc
    [
TypeError: 'int' object is not iterable
2025-09-19 14:41:42,247 [INFO] __main__: Uploading object: AIInsightFeedback
2025-09-19 14:41:42,248 [DEBUG] urllib3.connectionpool: Starting new HTTPS connection (1): cretemechanical.atlassian.net:443
2025-09-19 14:41:42,334 [DEBUG] urllib3.connectionpool: https://cretemechanical.atlassian.net:443 "GET /wiki/api/v2/pages?spaceId=28180482&title=AIInsightFeedback&expand=version HTTP/1.1" 200 None
2025-09-19 14:41:42,335 [ERROR] __main__: Failed to upload object AIInsightFeedback
Traceback (most recent call last):
  File "C:\Users\vm-bpa\OneDrive - Crete Mechanical\Code\UploadFlowDocumentation\main.py", line 51, in process_objects
    uploader.upload_object_doc(parent_id=parent_id, object_name=obj_name, fields=fields, meta=meta)
  File "C:\Users\vm-bpa\OneDrive - Crete Mechanical\Code\UploadFlowDocumentation\confluence_uploader.py", line 145, in upload_object_doc
    [
TypeError: 'int' object is not iterable
2025-09-19 14:41:42,335 [INFO] __main__: Uploading object: AIInsightReason
2025-09-19 14:41:42,336 [DEBUG] urllib3.connectionpool: Starting new HTTPS connection (1): cretemechanical.atlassian.net:443
2025-09-19 14:41:42,420 [DEBUG] urllib3.connectionpool: https://cretemechanical.atlassian.net:443 "GET /wiki/api/v2/pages?spaceId=28180482&title=AIInsightReason&expand=version HTTP/1.1" 200 None
2025-09-19 14:41:42,420 [ERROR] __main__: Failed to upload object AIInsightReason
Traceback (most recent call last):
  File "C:\Users\vm-bpa\OneDrive - Crete Mechanical\Code\UploadFlowDocumentation\main.py", line 51, in process_objects
    uploader.upload_object_doc(parent_id=parent_id, object_name=obj_name, fields=fields, meta=meta)
  File "C:\Users\vm-bpa\OneDrive - Crete Mechanical\Code\UploadFlowDocumentation\confluence_uploader.py", line 145, in upload_object_doc
    [
TypeError: 'int' object is not iterable
2025-09-19 14:41:42,421 [INFO] __main__: Uploading object: AIInsightValue
2025-09-19 14:41:42,422 [DEBUG] urllib3.connectionpool: Starting new HTTPS connection (1): cretemechanical.atlassian.net:443
2025-09-19 14:41:42,476 [DEBUG] urllib3.connectionpool: https://cretemechanical.atlassian.net:443 "GET /wiki/api/v2/pages?spaceId=28180482&title=AIInsightValue&expand=version HTTP/1.1" 200 None
2025-09-19 14:41:42,477 [ERROR] __main__: Failed to upload object AIInsightValue
Traceback (most recent call last):
  File "C:\Users\vm-bpa\OneDrive - Crete Mechanical\Code\UploadFlowDocumentation\main.py", line 51, in process_objects
    uploader.upload_object_doc(parent_id=parent_id, object_name=obj_name, fields=fields, meta=meta)
  File "C:\Users\vm-bpa\OneDrive - Crete Mechanical\Code\UploadFlowDocumentation\confluence_uploader.py", line 145, in upload_object_doc
    [
TypeError: 'int' object is not iterable
2025-09-19 14:41:42,478 [INFO] __main__: Uploading object: AIPredictionEvent
2025-09-19 14:41:42,479 [DEBUG] urllib3.connectionpool: Starting new HTTPS connection (1): cretemechanical.atlassian.net:443
2025-09-19 14:41:42,531 [DEBUG] urllib3.connectionpool: https://cretemechanical.atlassian.net:443 "GET /wiki/api/v2/pages?spaceId=28180482&title=AIPredictionEvent&expand=version HTTP/1.1" 200 None
2025-09-19 14:41:42,531 [ERROR] __main__: Failed to upload object AIPredictionEvent
Traceback (most recent call last):
  File "C:\Users\vm-bpa\OneDrive - Crete Mechanical\Code\UploadFlowDocumentation\main.py", line 51, in process_objects
    uploader.upload_object_doc(parent_id=parent_id, object_name=obj_name, fields=fields, meta=meta)
  File "C:\Users\vm-bpa\OneDrive - Crete Mechanical\Code\UploadFlowDocumentation\confluence_uploader.py", line 200, in upload_object_doc
    for cr in meta.get("childRelationships", []):
TypeError: 'int' object is not iterable
